title: Digital IC Designer learning
description: >-
  hi guys, I'm a undergraduate in Shenzhen University, might study for a
  master's degree in the future.The Digital IC Designer I plan to do is a pretty
  challenging job, that mean I should learn more and more deep knowledge.Thus, I
  opened my blog to record.
template:
  repo: digital-ic-designer-learning-template
  name: digital-ic-designer-learning
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
